### ISSUE TITLE
Epic: Add Google Analytics tracking to the frontend docs site

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend-docs#133]
## What
This work looks at adding Google Tag Manager and Google Analytics on [frontend.design-system.service.gov.uk](https://frontend.design-system.service.gov.uk/#gov-uk-frontend). This follows on from work to add it to the design system: https://github.com/alphagov/govuk-design-system/issues/1610. Ideally this uses the same cookie and we make use of sub-domain consent.

## Why
We want to include GA on tracking back on the Frontend Docs site so that we can better understand how our users are engaging with the website. We can then use this data to learn and improve more about the Frontend Docs.

## Who needs to know about this
Developers, Performance Analyst, Content Designer

## Done when
- [ ] [Decide approach for sub-domain consent](https://github.com/alphagov/govuk-design-system/issues/1613)
- [ ] Tweak existing govuk-design-system cookie consent functions to handle sub-domain consent
- [ ] [Add cookie consent functions in the frontend docs](https://github.com/alphagov/govuk-frontend-docs/issues/118)
- [ ] [Add Google Tag Manager code to the frontend docs](https://github.com/alphagov/govuk-frontend-docs/issues/119)
- [ ] [Add cookie banner to frontend docs](https://github.com/alphagov/govuk-design-system/issues/1619)
- [ ] Decide on approach for cookie page - linking to the design system page?
- [ ] Reset the banner for users if switching from design-system only consent to sub-domain consent
