### ISSUE TITLE
Announce upcoming v5.0 changes for digital team managers and leaders

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend-docs#321]
## What

Write and publish an announcement of what's coming in v5.0 and the impact it'll have on service teams and their roadmaps. Intended audience is product managers, service owners, and digital function senior managers/leaders.

## Why

The changes in v5.0 will have an impact on teams' roadmaps and we want to give them advance notice, so that they can factor it into their planning. We also want to create an opportunity for managers of teams to get in touch with any queries, as we have good contact with designers and developers in service teams already.

## Who needs to know about this

Ollie, Claire, Steve.
```[tasklist]
### Tasks
- [x] Draft the announcement
- [x] Get it checked by Comms
- [x] Find out how to reach digital function leaders
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/322
- [ ] Duplicate announcement on govuk-frontend repo announcements
```

**Comment by stevenjmesser** [comment]
Here's the [announcement](https://docs.google.com/document/d/14iyNSYxS7IghIqQevIh9vNSX3AitBD6YoR_kSilfTd0/) (internal doc) that @36degrees and I wrote.

**Comment by stevenjmesser** [comment]
Have shared the doc with @claireashworth to get her thoughts on where we could publish it on the Frontend docs site.

**Comment by stevenjmesser** [comment]
Announcement published as a [hidden page on Frontend docs](https://frontend.design-system.service.gov.uk/v5-0-announcement/). I've shared with people who can get this in front of Heads Of in departments.

Last thing is to add an announcement to the Discussions section on govuk-frontend repo, but I'm not sure I have the permissions needed to do that. Will investigate.
